### PR TITLE
Warnings removal

### PR DESCRIPTION
**Pull request by tommai78101**
This is an ongoing effort to remove as many unnecessary warnings as much as possible. 

**Removed all warnings. May be mergeable.**

Goals:

* Aim to remove all warnings.     
* Any improvements / edits are considered to be icing on a small cake.

Removing warnings will allow us to find hidden bugs. Cases in point:

* [Exhibit A](https://github.com/44670/NTR/blob/master/source/plg.c#L313) - We know this function takes a parameter, but here, this doesn't. Thus, GCC throws a warning at us.
* [Exhibit B](https://github.com/44670/NTR/blob/c764c0f68c08f3518a9f284f5fda1bf3b2636123/source/ns/rt.c#L211) - This function is missing its declaration in the svc.h, so it's technically "ignored" by the compiler...
* [Exhibit C](https://github.com/44670/NTR/pull/5/commits/b807ff6536d727e34135d5e101badf5353e4254d#diff-28edcff6b9dcc3e4cbc9216d2f3b610aR40) - svc_openThread() is missing in svc.h.
* [Exhibit D](https://github.com/44670/NTR/blob/c764c0f68c08f3518a9f284f5fda1bf3b2636123/source/svc7b.c#L18-L21) - Uh...

You sort of get the idea why removing warnings is important.

### CODE REVIEW

**Comment by tommai78101** [comment]
In regards to this code:

https://github.com/44670/NTR/blob/c764c0f68c08f3518a9f284f5fda1bf3b2636123/source/plg.c#L722

> <@booto> in C, you'd normally use an explicit cast... but possibly the type chosen for arm11BinStart should be reconsidered

**Comment by tommai78101** [comment]
In many places, such as:

https://github.com/44670/NTR/blob/c764c0f68c08f3518a9f284f5fda1bf3b2636123/source/plg.c#L693

> <+PlanckWalk> wedr_: I mean heck, they explcitly use u32 as an address type :-(

I should probably learn how to refactor those codes, so it uses the correct u32* pointer types, instead of pure u32.

**Comment by 44670** [comment]
wow!

**Comment by tommai78101** [comment]
Hi, please let me know if you think something else should be changed?

**Comment by 44670** [comment]
I have taken a quick look at the diff, should be okay. Tests are needed.

**Pull request merged**
